spring:
  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 1000 # 连接池大连接数（使用负值表示没有限制）
        max-idle: 1000 # 连接池中的大空闲连接
        min-idle: 10 # 连接池中的小空闲连接
        max-wait: 1000 # 连接池大阻塞等待时间（使用负值表示没有限制）
        shutdown-timeout: 100   # 关闭超时时间
    database: 0
  datasource:
#    47.114.41.69
    url: jdbc:mysql://103.143.80.89:13245/sports_info?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
#    username: root
#    f6LHtzCktMyR3dGC
    username: sports_info
    password: f6LHtzCktMyR3dGC
    dbcp2:
      initial-size: 5
      min-idle: 5
      max-idle: 50
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 30000

enableHttpProxy: true