spring:
  # 环境 aliyun:集成测试环境|pre:预生产环境|prd:生成环境|tencent:腾讯云
  profiles:
    active: tencent
#    active: aliyun
  mail:
    username: xxx
    password: xxx
    default-encoding: UTF-8
    host: smtp.qq.com
    port: 465

    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          port: ${spring.mail.port}
          auth: true
          starttls:
            enable: true
            required: true
  mvc:
    static-path-pattern: /static/**
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# Mybatis配置
mybatis:
  configLocation: classpath:mybatis.xml
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/xy/sports/**/mapper/*.xml

logging:
  level:
    -com.bottle.pay.modules.sys.dao: debug
    -com.bottle.pay.modules.api.dao: debug
    -com.bottle.pay.modules.biz.dao: debug
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  pageSizeZero: false #pageSize=0

#http配置服务
#最大连接数
http:
  maxTotal: 100
#并发数
  defaultMaxPerRoute: 20
#创建连接的最长时间
  connectTimeout: 1000
#从连接池中获取到连接的最长时间
  connectionRequestTimeout: 500
#数据传输的最长时间
  socketTimeout: 50000
#提交请求前测试连接是否可用
  staleConnectionCheckEnabled: true

# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
  port: 14000
  servlet:
    context-path: /sports-info

# 系统自定义全局配置，可根据实际需要扩展使用
global:
  upload-location: /home/sports-info #文件上传目录
  upload-mapping: /upload/ #文件上传目录访问路径
  redis-session-dao: true #是否使用使用redis会话管理器，true为开启，false为关闭
  kaptcha-enable: false #是否开启验证码，true为开启，false为关闭

# jwt配置
jwt:
  secret: Kmf2EQcaVFm7RzoS  #jwt密钥
  expiration: 604800  #过期时间,秒
merchant:
  billOutLimit: 50000   #自动出款上线额度，超出额度要手动派单

log:
  level:
    root: info

  file: ../sports-info/sports-info.log
  maxsize: 20MB